### ISSUE TITLE
Selenoid images with Firefox can't create a new driver instance

### ISSUE THREAD

**Issue by GlitchTQ** [wrike/callisto-chart#12]
Hi!
I decided to use Callisto as API for creating many browsers and use sessionID for tests run.
I deployed 3 Callisto's exemplars with Chrome and all is great.
Although exemplar with Firefox return next error:

```
--- x11vnc loop: 1 ---
08:23:41.972 INFO - Launching a standalone Selenium Server
08:23:41.996 INFO - Java: Oracle Corporation 25.151-b12
08:23:41.996 INFO - OS: Linux 5.3.18-lp152.23-default amd64
--- x11vnc loop: waiting for: 51
08:23:42.069 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
PORT=5900
08:23:42.273 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
08:23:42.273 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
08:23:42.273 INFO - Driver class not found: com.opera.core.systems.OperaDriver
08:23:42.273 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
08:23:42.274 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
08:23:42.275 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
08:23:42.275 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
08:23:42.387 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
08:23:42.388 INFO - Selenium Server is up and running
08:23:46.639 INFO - Executing: [new session: Capabilities [{browser=Firefox}]])
08:23:46.671 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: The best matching driver provider Firefox/Marionette driver can't create a new driver instance for Capabilities [{browser=Firefox}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'browser-qjvqs', ip: '10.42.7.9', os.name: 'Linux', os.arch: 'amd64', os.version: '5.3.18-lp152.23-default', java.version: '1.8.0_151'
Driver info: driver.version: unknown
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: The best matching driver provider Firefox/Marionette driver can't create a new driver instance for Capabilities [{browser=Firefox}]
```

Requst example for creating browser:
```
POST http://callisto.local/session

{
  "desiredCapabilities": {
    "browser": "firefox"
  }
}
```

I use default images from Helm-chart.
Can you help me find the way to solve this?

**Comment by mihailsaver** [comment]
Faced same issue, update to lates images and it will work
